add test command

diff --git a/try b/try
--- a/try
+++ b/try
@@ -19,3 +19,16 @@ while true; do
             ;;
     esac
 done
+
+for (( i=1; i<=$number; i++ )); do
+    
+    $command > /dev/null
+    if [[ $? -eq 0 ]]; then
+        echo "Succed after $i try."
+        exit 0
+    else 
+        sleep $interval
+    fi
+done
+echo "Test failed after $number try." 1>&2;
+exit 1
